<?php
/**
 * Thin PHP wrapper for the 404 page.
 * Serves the static 404.html generated by Eleventy with a proper
 * HTTP 404 status so search engines don't index missing pages.
 * Returns JSON when the client sends Accept: application/json
 * (or similar JSON media types) so AI agents get structured errors.
 */

http_response_code(404);

$accept = $_SERVER['HTTP_ACCEPT'] ?? '';

if (preg_match('#application/(?:\*\+)?json|application/\*#i', $accept)) {
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode([
        'error' => 'not_found',
        'status' => 404,
        'message' => 'The requested page was not found.',
        'homepage' => 'https://wikizeit.jcubic.pl/',
    ], JSON_UNESCAPED_SLASHES);
    exit;
}

$html = file_get_contents(__DIR__ . '/404.html');

if ($html === false) {
    exit('Not Found');
}

echo $html;
